---
version: '3'

services:
  picodata-1:
      image: docker-public.binary.picodata.io/picodata:25.2.3
      container_name: picodata-1
      hostname: picodata-1
      environment:
        PICODATA_INSTANCE_NAME: picodata-1
        PICODATA_INSTANCE_DIR: picodata-1
        PICODATA_IPROTO_LISTEN: picodata-1:3301
        PICODATA_IPROTO_ADVERTISE: picodata-1:3301
        PICODATA_PEER: picodata-1:3301
        PICODATA_PG_LISTEN: picodata-1:4327
        PICODATA_PG_SSL: "false"
        PICODATA_ADMIN_PASSWORD: "T0psecret"
      ports:
      - "3301:3301"
      - "4327:4327"

  picodata-2:
      image: docker-public.binary.picodata.io/picodata:25.2.3
      container_name: picodata-2
      hostname: picodata-2
      depends_on:
      - picodata-1
      environment:
        PICODATA_INSTANCE_NAME: picodata-2
        PICODATA_INSTANCE_DIR: picodata-2
        PICODATA_IPROTO_LISTEN: picodata-2:3302
        PICODATA_IPROTO_ADVERTISE: picodata-2:3302
        PICODATA_PG_LISTEN: picodata-2:4328
        PICODATA_PG_SSL: "false"
        PICODATA_PEER: picodata-1:3301
      ports:
      - "3302:3302"
      - "4328:4328"


  picodata-3:
      image: docker-public.binary.picodata.io/picodata:25.2.3
      container_name: picodata-3
      hostname: picodata-3
      depends_on:
      - picodata-1
      environment:
        PICODATA_INSTANCE_NAME: picodata-3
        PICODATA_INSTANCE_DIR: picodata-3
        PICODATA_IPROTO_LISTEN: picodata-3:3303
        PICODATA_IPROTO_ADVERTISE: picodata-3:3303
        PICODATA_PG_LISTEN: picodata-3:4329
        PICODATA_PG_SSL: "false"
        PICODATA_PEER: picodata-1:3301
      ports:
      - "3303:3303"
      - "4329:4329"